### ISSUE TITLE
Latest version pulling in woodstox vulnerability.

### ISSUE THREAD

**Issue by andrewhallambc** [damianszczepanik/silencio#156]
Hi @damianszczepanik
Your latest version 2.4.2 still has the woodstox vulnerability - due to the fact you are pulling in jackson 2.13.*
See -
| --- pl.damianszczepanik:silencio:2.4.2
| +--- com.fasterxml.jackson.core:jackson-databind:2.13.4 -> 2.13.4.2 ()
| +--- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.13.4
| | +--- com.fasterxml.jackson.core:jackson-core:2.13.4 ()
| | +--- com.fasterxml.jackson.core:jackson-annotations:2.13.4 ()
| | +--- com.fasterxml.jackson.core:jackson-databind:2.13.4 -> 2.13.4.2 ()
| | +--- org.codehaus.woodstox:stax2-api:4.2.1
| | +--- com.fasterxml.woodstox:woodstox-core:6.3.1
| | | --- org.codehaus.woodstox:stax2-api:4.2.1
| | --- com.fasterxml.jackson:jackson-bom:2.13.4 (*)

The vulnerability fix to jackson if from 2.14.0 onwards (pulls in woodstox-core:6.4.0).

![image](https://user-images.githubusercontent.com/13450055/204581801-3890685f-8cd0-4aa3-b78b-1e41523faa9a.png)

Could you please update your lib to at least 2.14.0 please.
Thanks

**Comment by damianszczepanik** [comment]
Ritht, use-latest-version does not work with variables

**Comment by damianszczepanik** [comment]
Published again
