### ISSUE TITLE
 if I want to invite people with my link via WhatApp.

### ISSUE THREAD

**Issue by wealthypreneur** [damianszczepanik/silencio#205]
I'm having problems with the app. if I want to invite people with my link via WhatApp. And they install the Silencio app. Then they can enter my invide code, after which they will further set up their account. When you click the email option, to set their email nothing happens. You can click on the email 10 times and it still won't go any further. When reinstalling, it happens again and again.
So I can't add people to my network.
Can anyone help me with this problem, because for my score it is necessary that I involve more users in the app!
Please help me

**Comment by damianszczepanik** [comment]
This is not the project that you are talking about

**Comment by wealthypreneur** [comment]
What do you mean. I cannot invite friends with my invitation code in the Silencio app.
This is about the Silencio airdrop that you have to complete. That's where I have problems.
What do you mean by that?
I'm writing this at Silencio on GitHub, right?
