### ISSUE TITLE
Transforming based on path

### ISSUE THREAD

**Issue by rs-01** [damianszczepanik/silencio#90]
How can I transform BatteryTemperatureInDc values which are only in path BatteryProcessInfoList/BatteryHistoryItemsList. Here is the sample JSON:
{
  "Level1Field1" : 2,
  "BatteryHistoryItemsList" : [ {
    "BatteryTemperatureInDc" : 28.6,
    "BatteryVoltageInMv" : 38.32
  }, {
    "BatteryTemperatureInDc" : 2.96,
    "BatteryVoltageInMv" : 39.19
  } ],
  "BatteryProcessInfoList" : [ {
    "CpuTimeInMs" : 0,
    "BatteryHistoryItemsList" : [ {
      "BatteryTemperatureInDc" : 28.6, "BatteryVoltageInMv" : 38.32
    }, {
      "BatteryTemperatureInDc" : 2.96, "BatteryVoltageInMv" : 3.919
    } ],
    "UsageTimeInMs" : 345047049
  }, {
    "CpuTimeInMs" : 65284460,
    "BatteryHistoryItemsList" : [ {
      "BatteryTemperatureInDc" : 28.6, "BatteryVoltageInMv" : 383.2
    } ],
    "UsageTimeInMs" : 0
  } ],
  "month" : 12
}

**Comment by damianszczepanik** [comment]
It supports transition of the values. Keys are not supported

**Comment by rs-01** [comment]
Thanks for a quick response. I am not looking to transform the keys. However, I would like to transform the values of attributes BatteryTemperatureInDc (in above example) which are in the path BatteryProcessInfoList/BatteryHistoryItemsList. I want to leave the values of this attribute unchanged if it is appearing at other places in the JSON. I tried to use MatcherDecision("BatteryTemperatureInDc", null). However, it matches with all attributes whose name is BatteryTemperatureInDc. I am looking for a way where matcher matches only this attribute if it is in path BatteryProcessInfoList/BatteryHistoryItemsList. I have written my converter and can filter other keys there if I can get hold of complete path.

Please let me know if there is a way.

**Comment by damianszczepanik** [comment]
Take a look at this example  https://github.com/damianszczepanik/silencio/blob/master/src/test/java/pl/szczepanik/silencio/integration/JSONProcessorIntegrationTest.java and if it does not help give some example before and after modification for the JSON

**Comment by rs-01** [comment]
Damian,

Here is JSON that I would like to modify:

{
	"Level1Field1": 2,
	"BatteryHistoryItemsList": [{
		"BatteryTemperatureInDc": 28.6,
		"BatteryVoltageInMv": 38.32
	}, {
		"BatteryTemperatureInDc": 2.96,
		"BatteryVoltageInMv": 39.19
	}],
	"BatteryProcessInfoList": [{
		"CpuTimeInMs": 0,
		"BatteryHistoryItemsList": [{
			**"BatteryTemperatureInDc": 28.6**,
			"BatteryVoltageInMv": 38.32
		}, {
			**"BatteryTemperatureInDc": 2.96**,
			"BatteryVoltageInMv": 3.919
		}],
		"UsageTimeInMs": 345047049
	}, {
		"CpuTimeInMs": 65284460,
		"BatteryHistoryItemsList": [{
			**"BatteryTemperatureInDc": 28.6**,
			"BatteryVoltageInMv": 383.2
		}],
		"UsageTimeInMs": 0
	}],
	"month": 12
}

After Modification:
{
	"Level1Field1": 2,
	"BatteryHistoryItemsList": [{
		"BatteryTemperatureInDc": 28.6,
		"BatteryVoltageInMv": 38.32
	}, {
		"BatteryTemperatureInDc": 2.96,
		"BatteryVoltageInMv": 39.19
	}],
	"BatteryProcessInfoList": [{
		"CpuTimeInMs": 0,
		"BatteryHistoryItemsList": [{
			**"BatteryTemperatureInDc": 28,**
			"BatteryVoltageInMv": 38.32
		}, {
			**"BatteryTemperatureInDc": 2**,
			"BatteryVoltageInMv": 3.919
		}],
		"UsageTimeInMs": 345047049
	}, {
		"CpuTimeInMs": 65284460,
		"BatteryHistoryItemsList": [{
			**"BatteryTemperatureInDc": 28**,
			"BatteryVoltageInMv": 383.2
		}],
		"UsageTimeInMs": 0
	}],
	"month": 12
}

In the above example, I would like to change the value of attribute "BatteryTemperatureInDc" from double to Int only if it is in path BatteryProcessInfoList/BatteryHistoryItemsList and want to keep it as is if it is not in this path. 
The above example has it in two different paths BatteryProcessInfoList/BatteryHistoryItemsList and BatteryHistoryItemsList. I want to do the conversion only in bold portion of the JSON

**Comment by rs-01** [comment]
Sorry - bold font did not work. Please let me know if it is not clear.

**Comment by damianszczepanik** [comment]
Looks like this is the typical case for this library. So what you need it to implement your own ``Converter``, you can take a look at this https://github.com/damianszczepanik/silencio/blob/master/src/main/java/pl/szczepanik/silencio/converters/NumberSequenceConverter.java and fill convert() method probably with something like:

``return new Value(new Double(value.getValue()).intValue());``

**Comment by rs-01** [comment]
I already did what you are suggesting. However, it ends up changing values everywhere of attribute "BatteryTemperatureInDc" irrespective of the path. I want the value to be changed only if it is in specified path.

**Comment by damianszczepanik** [comment]
OK, you need to add condition when the value should be changed. Probably something like

```
if ("BatteryTemperatureInDc".equals(value.getValue())) {
  return updated value;
} else {
  return value;
}
```

**Comment by rs-01** [comment]
The whole issue is that key only has attribute name. It does not have path info. I need path info to filter out the paths that do not require transformation.

**Comment by damianszczepanik** [comment]
Ok now I see. It is not supported. I would have to check if can be and provide such information about context.

**Comment by rs-01** [comment]
Thanks for your quick responses. I ended up directly using Jackson APIs.
